Auth Service: Convert to Helm
sciurus/taskcluster pull request #15
Opened 2019-05-21 04:15 UTC by edunham

Need to figure out that json-e list and also the right way to handle all those locals (current strategy of ignoring them is obviously great for writing boilerplate and awful for emitting a working service)

2019-05-24 18:33 UTC, sciurus commented on infrastructure/k8s/services/auth.yaml
> +  azure_accounts: "" # FIXME this was "${jsonencode(map( "${azurerm_storage_account.base.name}", "${azurerm_storage_account.base.primary_access_key}",))}"
As a first pass I'd put the json for `{account_name: access_key}` as a single string in sops.

2019-05-24 18:43 UTC, sciurus requested changes
As a first pass at `static_clients` I would just build the JSON for that list and stick it in sops as a string then look it ip.

2019-05-24 18:43 UTC, sciurus commented on infrastructure/k8s/services/auth.yaml
> +  sentry_api_key: ".Values.sentryApiKey"
Can you check if they still use sentry?

2019-06-12 21:37 UTC, edunham commented
r+ from me on this -- let's see how the blob in sops goes!

2019-06-14 14:19 UTC, sciurus commented
I think this still needs some work, but it's starting up, so I'll consider that mergeable.

2019-06-14 14:20 UTC, merged