Cron yaml matches cluster
sciurus/taskcluster pull request #4
Opened 2019-05-16 21:18 UTC by edunham

This is the changeset that makes helmit's output look exactly like the kubectl export. 

Let's discuss whether including the null `creationTimestamp` (it's null across all crons in the cluster as retrieved w/ kubectl), the empty `status`, etc are actually things we should be including ourselves or if they came from kubernetes.

2019-05-16 21:22 UTC, edunham commented
Just realized this does not *quite* match the cluster -- I omitted the giant wall of configs under 

```metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
```

because they look to me like kubectl storing its own state and not something we should be telling it

2019-05-16 21:33 UTC, sciurus requested changes
For the new keys you added, e.g. concurrencyPolicy, failedJobsHistoryLimit, etc, I don't think we need to explicitly set any of them. We can just use the defaults, like their templates do now. I think if you run `kubectl` against the taskcluster-nonprod cluster that we have, you'll see that they are set for us.

The `upper` bits LGTM. I wonder, do you need to do that in the secrets template to so they match? I.E.

` ${uppercase(s.key)}: "{{ ${s.val} | b64enc }}`

2019-05-16 21:34 UTC, sciurus commented
Below is the YAML for the purge cache cron deployed to our taskcluster-nonprod cluster now.

```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"batch/v1beta1","kind":"CronJob","metadata":{"annotations":{},"name":"taskcluster-purge-cache-expirecachepurges","namespace":"default"},"spec":{"jobTemplate":{"metadata":{"labels":{"application":"taskcluster","taskcluster-service":"taskcluster-purge-cache"}},"spec":{"template":{"spec":{"activeDeadlineSeconds":86400,"containers":[{"args":["purge-cache/expireCachePurges"],"env":[{"name":"TASKCLUSTER_ROOT_URL","value":"example.com"},{"name":"taskcluster_client_id","valueFrom":{"secretKeyRef":{"key":"taskcluster_client_id","name":"taskcluster-purge-cache"}}},{"name":"taskcluster_access_token","valueFrom":{"secretKeyRef":{"key":"taskcluster_access_token","name":"taskcluster-purge-cache"}}},{"name":"force_ssl","valueFrom":{"secretKeyRef":{"key":"force_ssl","name":"taskcluster-purge-cache"}}},{"name":"trust_proxy","valueFrom":{"secretKeyRef":{"key":"trust_proxy","name":"taskcluster-purge-cache"}}},{"name":"node_env","valueFrom":{"secretKeyRef":{"key":"node_env","name":"taskcluster-purge-cache"}}},{"name":"monitoring_enable","valueFrom":{"secretKeyRef":{"key":"monitoring_enable","name":"taskcluster-purge-cache"}}},{"name":"publish_metadata","valueFrom":{"secretKeyRef":{"key":"publish_metadata","name":"taskcluster-purge-cache"}}},{"name":"azure_account","valueFrom":{"secretKeyRef":{"key":"azure_account","name":"taskcluster-purge-cache"}}}],"image":"bar","imagePullPolicy":"Always","name":"taskcluster-purge-cache-expirecachepurges","resources":{"requests":{"cpu":"100m","memory":"100Mi"}}}],"restartPolicy":"OnFailure"}}}},"schedule":"0 0 * * *"}}
  creationTimestamp: 2019-05-15T18:01:30Z
  name: taskcluster-purge-cache-expirecachepurges
  namespace: default
  resourceVersion: "5217104"
  selfLink: /apis/batch/v1beta1/namespaces/default/cronjobs/taskcluster-purge-cache-expirecachepurges
  uid: 777c2a9f-773b-11e9-b45f-42010a8a00d9
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
      labels:
        application: taskcluster
        taskcluster-service: taskcluster-purge-cache
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          activeDeadlineSeconds: 86400
          containers:
          - args:
            - purge-cache/expireCachePurges
            env:
            - name: TASKCLUSTER_ROOT_URL
              value: example.com
            - name: taskcluster_client_id
              valueFrom:
                secretKeyRef:
                  key: taskcluster_client_id
                  name: taskcluster-purge-cache
            - name: taskcluster_access_token
              valueFrom:
                secretKeyRef:
                  key: taskcluster_access_token
                  name: taskcluster-purge-cache
            - name: force_ssl
              valueFrom:
                secretKeyRef:
                  key: force_ssl
                  name: taskcluster-purge-cache
            - name: trust_proxy
              valueFrom:
                secretKeyRef:
                  key: trust_proxy
                  name: taskcluster-purge-cache
            - name: node_env
              valueFrom:
                secretKeyRef:
                  key: node_env
                  name: taskcluster-purge-cache
            - name: monitoring_enable
              valueFrom:
                secretKeyRef:
                  key: monitoring_enable
                  name: taskcluster-purge-cache
            - name: publish_metadata
              valueFrom:
                secretKeyRef:
                  key: publish_metadata
                  name: taskcluster-purge-cache
            - name: azure_account
              valueFrom:
                secretKeyRef:
                  key: azure_account
                  name: taskcluster-purge-cache
            image: bar
            imagePullPolicy: Always
            name: taskcluster-purge-cache-expirecachepurges
            resources:
              requests:
                cpu: 100m
                memory: 100Mi
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: 0 0 * * *
  successfulJobsHistoryLimit: 3
  suspend: false
status:
  active:
  - apiVersion: batch/v1
    kind: Job
    name: taskcluster-purge-cache-expirecachepurges-1557964800
    namespace: default
    resourceVersion: "5217103"
    uid: 906746c0-776d-11e9-9a58-42010a8a0152
  lastScheduleTime: 2019-05-16T00:00:00Z
```

2019-05-17 16:42 UTC, sciurus approved these changes

2019-05-21 02:09 UTC, merged