Web UI: Convert to Helm.
sciurus/taskcluster pull request #6
Opened 2019-05-21 02:21 UTC by edunham

There's probably a better way of doing those endpoint values.

2019-05-23 17:58 UTC, sciurus requested changes

2019-05-23 17:58 UTC, sciurus commented on infrastructure/terraform/to_review/web-ui.tf
> -  memory         = "400Mi"
We'll likely go back and adjust all of them alter, but let's port cpu and memory over under the assumption that they changed these from their deployment templates defaults for a reason.

2019-05-23 17:58 UTC, sciurus commented on infrastructure/k8s/services/web-ui.yaml
> +  taskcluster_client_id: "static/taskcluster/web-ui"
I don't see a client id this in the terraform.

2019-05-23 17:58 UTC, sciurus commented on infrastructure/k8s/services/web-ui.yaml
> +  login_strategies: ""
You're missing application_name.

2019-05-23 18:03 UTC, sciurus commented
So with our current system there is no better way of doing the endpoint values. If we need to do this in enough places we could change helmit so we can pass through a template expression instead of magically detecting .Values and wrapping in one.

2019-05-23 20:03 UTC, edunham commented
This was the only place we used the endpoint vals.

2019-05-28 19:00 UTC, sciurus approved these changes

2019-05-29 19:48 UTC, merged